const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
const root = path.resolve(__dirname, '..');
(async () => {
  fs.mkdirSync(path.join(root, 'qa'), {recursive:true});
  const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--enable-unsafe-swiftshader']});
  const page = await browser.newPage({viewport:{width:1440,height:940}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto('http://127.0.0.1:8090/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.sjlDiagnostics,{timeout:120000});
  await page.waitForTimeout(1800);
  console.log(JSON.stringify({desktop:await page.evaluate(()=>window.sjlDiagnostics()),errors}));
  await page.screenshot({path:path.join(root,'qa/desktop.png')});
  await page.locator('#scene canvas').screenshot({path:path.join(root,'qa/canvas.png')});
  await page.locator('#placeSearch').fill('Estación Santa Rosa');
  await page.locator('#searchGo').click();
  await page.waitForTimeout(2200);
  await page.screenshot({path:path.join(root,'qa/closeup.png')});
  await page.locator('#toggleView').click();
  await page.waitForTimeout(2200);
  await page.screenshot({path:path.join(root,'qa/overview.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#resetView').click();
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForTimeout(2200);
  await page.screenshot({path:path.join(root,'qa/mobile.png')});
  await page.locator('#scene canvas').screenshot({path:path.join(root,'qa/mobile-canvas.png')});
  console.log(JSON.stringify({mobile:await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:document.querySelector('#scene canvas').getBoundingClientRect().toJSON()})),errors}));
  await page.setViewportSize({width:320,height:844});
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(root,'qa/mobile-320.png')});
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
