const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const checks=[];
const pass=name=>{checks.push(name);console.log('PASS '+name);};
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:940}});
  const page=await context.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('http://127.0.0.1:8090/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.sjlDiagnostics,{timeout:120000});
  const initial=await page.evaluate(()=>sjlDiagnostics());
  assert.equal(initial.buildings,5044);assert.equal(initial.roads,17149);assert.ok(initial.estimated>70000);pass('Real geography and full urban scene loaded');
  const before=await page.evaluate(()=>sjlMap.camera.position.toArray());
  await page.locator('#tourButton').click();await page.waitForTimeout(1500);
  const after=await page.evaluate(()=>sjlMap.camera.position.toArray());
  assert.notDeepEqual(after,before);assert.equal(await page.locator('#tourButton').getAttribute('aria-pressed'),'true');
  await page.locator('#tourButton').click();pass('Aerial tour starts, moves and pauses');
  await page.locator('#resetView').click();await page.waitForTimeout(1800);
  const canvas=page.locator('#scene canvas'),box=await canvas.boundingBox();
  const orbitStart=await page.evaluate(()=>sjlMap.camera.position.toArray());
  await page.mouse.move(box.x+box.width*.46,box.y+box.height*.53);await page.mouse.down();await page.mouse.move(box.x+box.width*.53,box.y+box.height*.56,{steps:12});await page.mouse.up();await page.waitForTimeout(500);
  assert.notDeepEqual(await page.evaluate(()=>sjlMap.camera.position.toArray()),orbitStart);pass('Pointer orbit changes camera');
  await page.locator('#placeSearch').fill('Estación Santa Rosa');await page.locator('#searchGo').click();await page.waitForTimeout(1900);
  const target=await page.evaluate(()=>sjlMap.controls.target.toArray());assert.ok(Math.abs(target[0]+98.9876)<1&&Math.abs(target[2]+1175.1482)<1);pass('Search uses the station projected onto the real Metro alignment');
  await page.locator('#showEstimated').uncheck();assert.equal(await page.evaluate(()=>sjlMap.infill.visible),false);
  await page.locator('#showBuildings').uncheck();await page.locator('#showBuildings').check();assert.equal(await page.evaluate(()=>sjlMap.infill.visible),false);
  await page.locator('#showEstimated').check();pass('Real and estimated building layers remain independently controlled');
  await page.locator('#newReport').click();
  await page.mouse.click(box.x+box.width*.59,box.y+box.height*.64);
  await page.locator('#reportModal').waitFor({state:'visible'});
  const picked=await page.locator('#issueCoordinates').textContent();assert.match(picked,/-11\.|-12\./);
  await page.locator('#issueTitle').fill('Vereda accesible pendiente de reparación');
  await page.locator('#issueDescription').fill('Prueba automatizada: el desnivel del cruce dificulta el paso de una silla de ruedas.');
  await page.locator('#reportForm button[type=submit]').click();
  assert.equal(await page.locator('#detailStatus').textContent(),'Reportado');
  let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('sjl3d-geographic-reports-v2')));
  assert.equal(stored.reports.length,6);assert.equal(stored.reports[0].status,'open');const created=stored.reports[0];
  assert.equal(await page.locator('#detailCoordinates').textContent(),picked);pass('Report created at clicked latitude/longitude and stored locally');
  await page.selectOption('#roleSelect','admin');await page.locator('#detailAction').click();assert.equal(await page.locator('#detailStatus').textContent(),'En atención');
  await page.selectOption('#roleSelect','technician');await page.locator('#detailAction').click();assert.equal(await page.locator('#detailStatus').textContent(),'Resuelto');
  stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('sjl3d-geographic-reports-v2')));assert.equal(stored.reports[0].history.length,3);pass('Admin assignment and technician resolution persist with audit history');
  await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.sjlDiagnostics,{timeout:120000});
  await page.locator('[data-id="'+created.id+'"]').click();assert.equal(await page.locator('#detailStatus').textContent(),'Resuelto');assert.equal(await page.locator('#detailCoordinates').textContent(),picked);pass('Reload preserves location, state and history');
  await page.locator('#detailAction').click();assert.equal(await page.locator('#detailHistory li').count(),3);pass('Citizen can inspect real stored follow-up history');
  await page.locator('#closeDetail').click();
  await page.locator('.layer-item input[value=access]').uncheck();assert.equal(await page.locator('[data-id="'+created.id+'"]').count(),0);assert.equal(await page.locator('[data-report="'+created.id+'"]').count(),0);pass('Category filters affect both map pins and report list');
  await page.locator('#seeAll').click();await page.locator('[data-id="R-041"]').click();await page.selectOption('#roleSelect','technician');await page.locator('#detailAction').click();
  stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('sjl3d-geographic-reports-v2')));assert.equal(stored.reports.find(r=>r.id==='R-041').status,'progress');pass('Updates to initial demo reports are preserved too');
  await page.locator('#closeDetail').click();await page.locator('#resetView').click();await page.waitForTimeout(1700);
  await page.screenshot({path:path.join(root,'qa/verified-desktop.png')});await canvas.screenshot({path:path.join(root,'qa/verified-canvas.png')});
  const cameraDownload=page.waitForEvent('download');await page.locator('#captureView').click();const captured=await cameraDownload;assert.equal(captured.suggestedFilename(),'sjl-corredor-3d.png');pass('Map image export');
  const exportWait=page.waitForEvent('download');await page.locator('#exportReports').click();const exported=await exportWait;assert.equal(exported.suggestedFilename(),'sjl-reportes.json');pass('Report JSON export');
  await page.locator('#aboutMap').click();assert.equal(await page.locator('#aboutModal').isVisible(),true);await page.locator('#closeAbout').click();pass('Source attribution and estimated-data disclosure available');
  for(const width of [390,320]){
    await page.setViewportSize({width,height:844});await page.waitForTimeout(500);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);
    await page.locator('#newReport').click();assert.equal(await page.locator('#placementBanner').isVisible(),true);await page.locator('#cancelPlacement').click();
    await page.screenshot({path:path.join(root,'qa/verified-mobile-'+width+'.png'),fullPage:true});
    pass('Mobile '+width+'px: no horizontal overflow and report controls usable');
  }
  await page.setViewportSize({width:1440,height:940});await page.locator('#toggleView').click();await page.waitForTimeout(1900);await page.screenshot({path:path.join(root,'qa/verified-overview.png')});
  const final=await page.evaluate(()=>sjlDiagnostics());
  assert.deepEqual(errors,[]);pass('No browser JavaScript or resource errors');
  fs.writeFileSync(path.join(root,'qa/test-results.json'),JSON.stringify({at:new Date().toISOString(),checks,initial,final,errors},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
